const playbase =[
    // Song Name Url Duration 
    {name:"Raatan Lambiya" , src: "Files/Raataan Lambiyan .mp3",duration:"03:50" ,singer:"jubin Nautiyal" ,category:"Bollywood" , genre:"happy"},
    {name:"Dheere Dheere" , src: "Files/Dheere Dheere.m4a",duration:"03:32" ,singer:"YoYo Honey Singh" ,category:"Bollywood",genre:"happy"},    
    {name: "Shaam-Lofi" , src: "Files/shaam.mp3" ,duration: "06:08" ,singer:"lofi", category:"Lofi" , genre:"cool"}, 
    {name: "Duniya" , src: "Files/Duniya.mp3" ,duration: "03:42" ,singer:"Abhijit Vakani", category:"bollywood", genre:"happy"}, 
    {name: "Parshawan" , src: "Files/Parshawan.mp3" ,duration: "02:55" ,singer:"Harnoor" ,category:"Punjabi",genre:"happy"}, 
    {name: "Tu hai Ki Nahi" , src: "Files/Tu_Hai_Ki_Nahi.mp3" ,duration: "05:34" ,singer:"Ankit tiwari" , category:"bollywood",genre:"sad"},
    {name:"Brown Munde" , src: "Files/Brown_Munde.mp3" ,duration:"04:27" ,singer:"ap Dhillon",category:"Punjabi",genre:"happy"},
    {name:"Zehra" , src: "Files/Zehra.mp3",duration:"03:48" ,singer:"Unknown",category:"single",genre:"happy"},
    {name:"Khaab" , src: "Files/Khaab.mp3",duration:"03:21",singer:"Akhil", category:"Punjabi",genre:"cool"},
    {name:"Dekhiya Kite" , src: "Files/Dekhya Kite.mp3",duration:"03:13",singer:"Simar Kaur", category:"Punjabi",genre:"happy"},
    {name:"Spain" , src: "Files/Spain.mp3",duration:"02:17",singer:"Jassa Dhillon", category:"Punjabi" , genre:"hifi"},
    {name:"Chann Sitare" , src: "Files/chann_sitare.mp3",duration:"03:07",singer:"Ammy virk", category:"Punjabi" , genre:"cool"},
    {name:"Relation" , src: "Files/Relation.mp3",duration:"03:30",singer:"Nikk", category:"Punjabi" ,genre: "happy"},
    {name:"Bapu Zimidar" , src: "Files/Bapu Zimidar.mp3",duration:"03:44",singer:"Jassi Gill", category:"Punjabi", genre:"hifi"},    
    {name:"Random" , src: "Files/videoplayback.mp3",duration:"03:13" ,singer:"Unknown",category:"single",genre:"cool"},
    {name: "Lahore" , src: "Files/Lahore (1).mp3" ,duration: "03:17",singer:"Guru Randhawa" , category:"bollywood" , genre:"happy"}, 
    {name:"Ranjha" , src: "Files/Ranjha.mp3",duration:"03:50" , singer:"b praak" , category:"bollywood" , genre:"sad"},
    {name:"Kuch Baatein" , src: "Files/Kuch-Baatein.mp3",duration:"04:58" , singer:"jubin Nautiyal" , category:"single",genre:"cool"},
    {name:"Lo Safar" , src: "Files/Lo Safar.mp3",duration:"04:41" ,singer:"jubin Nautiyal" ,category:"Bollywood" , genre:"sad"},
    {name:"Rim Jhim" , src: "Files/Rim_Jhim.mp3",duration:"03:46" ,singer:"jubin Nautiyal" ,category:"Bollywood",genre:"happy"},
    {name: "Challeya" ,src:"Files/Chaleya.mp3" , duration: "03:20" , category:"bollywood"  , genre:"happy"},  
    {name:"Lut Gaye" , src: "Files/Lut Gaye.mp3",duration:"03:48" ,singer:"jubin Nautiyal" ,category:"Bollywood",genre:"happy"},
    {name:"Humnava Mere" , src: "Files/Humnava Mere.mp3",duration:"05:29" ,singer:"jubin Nautiyal" ,category:"Bollywood",genre:"sad"},
    {name:"Barsaat Ki Dhum" , src: "Files/Barsaat Ki Dhun.mp3",duration:"05:42" ,singer:"jubin Nautiyal" ,category:"Bollywood",genre:"happy"},
    {name:"Meri Zindagi Hai Tu" , src: "Files/Meri Zindagi Hai.mp3",duration:"03:39" ,singer:"jubin Nautiyal" ,category:"Bollywood",genre:"cool"},
    {name:"Saibo Lofi" , src: "Files/saiboLofi.mp3",duration:"02:27" ,singer:"Shreya Ghosal" ,category:"lofi",genre:"sad"},
    {name:"Hawayein Lofi" , src: "Files/hawayeinLofi.mp3",duration:"03:57" ,singer:"pritam" ,category:"lofi",genre:"sad"},
    {name:"Banjaara Lofi" , src: "Files/banjaaraLofi.mp3",duration:"06:06" ,singer:"Mithoon" ,category:"lofi",genre:"sad"},
    {name:"kabira Lofi" , src: "Files/kabiraLofi.mp3",duration:"03:15" ,singer:"Rekha bhardwaj" ,category:"lofi",genre:"sad"},
    {name:"Phir Bhi Tumko Lofi" , src: "Files/Phir Bhi Tumko.m4a",duration:"05:20" ,singer:"Arijit" ,category:"lofi",genre:"sad"},
    {name:"Bheed Mein Lofi" , src: "Files/BheedMein.mp3",duration:"04:42" ,singer:"Udit Narayan" ,category:"lofi",genre:"cool"},
    {name:"Khamoshiya Lofi" , src: "Files/Khamoshiyan Lofi.mp3",duration:"03:03" ,singer:"Arijit" ,category:"lofi" , genre:"sad"},
    {name:"Ek Din Aap Lofi" , src: "Files/Ek Din Aap Lofi.mp3",duration:"04:29" ,singer:"Kumar Sanu" ,category:"lofi",genre:"classical"},
    {name:"Vail" , src: "Files/VAIL.m4a",duration:"04:01" ,singer:"Mankirt Aulak" ,category:"Punjabi"},
    {name:"Tum HO" , src: "Files/Tum Ho.m4a",duration:"05:22" ,singer:"Unknown" ,category:"Lofi",genre:"slow"},
    { name: "Aisi Teri Yaadein", src: "Files/Aisi Teri Yaadein.mp3", duration: "05:02", singer: "jubin Nautiyal", category: "bollywood",genre:"cool" },
    { name: "Ikk Number", src: "Files/Ikk Number.mp3", duration: "03:09", singer: "gurnam Bhullar", category:"Punjabi" , genre:"happy" },
    { name: "Lambiyaan Si Judaiyaan", src: "Files/Lambiyaan Si Judaiyaan.m4a", duration: "04:18", singer:"Arijit", category:"bollywood",genre:"sad" },
    { name: "Mera Mehboob", src: "Files/Mera Mehboob.m4a", duration:"03:27", singer:"stebin Ben", category:"single" , genre:"sad" },
    { name: "Mera Yaar", src: "Files/Mera Yaar.m4a", duration: "04:20", singer: "Gurnam Bhullar", category:"punjabi",genre:"sad" },
    { name: "Moonlight", src: "Files/Moonlight.mp3", duration: "03:34", singer: "Harnoor", category: "single" , genre:"happy" },
    { name: "Pindan de Jaye", src: "Files/Pindan de Jaye.mp3", duration: "04:57", singer: "sajjan Adeeb", category: "punjabi", genre:"happy" },
    { name: "System Se System", src: "Files/System Se System.m4a", duration: "03:57", singer: "r Maan", category:"single" , genre:"hifi" },
    { name: "Tenu Na Bol Pawaan", src: "Files/Tenu Na Bol Pawaan.m4a", duration: "05:00", singer: "yasser Desai", category:"bollywood" , genre : "cool" },

    ]
export function allSongs() {
    return playbase;
}
